### PR TITLE
Allow lang server restart

### PR DESCRIPTION
**Pull request by clayreimann**
A bunch of refactoring as well as adding commands for `swift clean`, `swift run`, and restarting the language server.

### CODE REVIEW

**Comment by vknabel** [comment]
Great changes so far!

**Comment by clayreimann** [comment]
@vknabel A lot of progress here. 

- The language server can be restarted (I've only confirmed `sourcekitd` because that's what I use)
- Added commands to `run`, `stop`, `clean`
- Cleaned up (IMO) the code for better understanding and maintenance

Could be merged as-is, but I think the configuration still needs to be cleaned up a bit. (It should all use the same prefix `sde.SECTION.setting` and I'd like to export an object from the configuration helper that mirrors the options–but allows us to hide the specific configuration names so we can migrate from what is to the new strings.)

**Comment by clayreimann** [comment]
Actually @vknabel I think it would make sense to merge this without the settings cleanup so we can better pinpoint where any bugs come from. 

This is already a pretty major rewrite and changing how we fetch config any more seems like asking for more headaches

**Comment by vknabel** [comment]
Hey @clayreimann. Sorry for the late response and a huge thank you for all your amazing work!

I have already started reviewing this PR. I will try to test everything as good as possible (on macOS and Linux), which is quite time consuming, but it will be worth it.

Once I find bugs, I will probably fix them directly, if that's okay for you. 

Currently I am not sure how we handle the release and renamed configs or commands. Technically it would be a breaking change and would require a major version bump. 
But this should be fine. 
Might be a great opportunity to delete unused features.

**Review by vknabel — APPROVED** [review]

**Comment by vknabel** [comment]
Thanks a lot @clayreimann!
I know it took quite a while. This PR really helps in the long term!
In https://github.com/vknabel/vscode-swift-development-environment/commit/b247437aece010a44341b91d51fa933c93d044ed I made a few fixes, added some changelogs and mentioned you in the README.

**Comment by vknabel** [comment]
I created a beta release tag: [2.11.0-beta.0](https://github.com/vknabel/vscode-swift-development-environment/releases/tag/2.11.0-beta.0).

I try to test it bit, but I believe it should work fine. Will release it soon.

**Pull request merged**
